version: "3.3"

services:
  app:
    image: inspectorio/prediction-io
    volumes:
    - ./:/home/pio/app/src
    - ~/.ssh:/home/pio/.ssh
    command:
    - /bin/bash
    - -c
    - 'trap : TERM INT; sleep infinity & wait'
    ports:
    - 7070:7070    # event server
    - 7071:7071    # dashboard
    - 8000:8000    # serving (spark application)
    - 9000:9000    # admin server
    environment:
      PIO_DB_HOST: postgres
      PIO_DB: pio
      PIO_DB_USER: pio
      PIO_DB_PASSWORD: pio
      ES_HOST: elasticsearch
      ES_PORT: 9200

  postgres:
    image: postgres:9.6
    environment:
      POSTGRES_USER: pio
      POSTGRES_PASSWORD: pio
      POSTGRES_DB: pio

  elasticsearch:
    image: elasticsearch:5.5.2
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - xpack.monitoring.enabled=false
      - xpack.watcher.enabled=false
    ports:
      - 9200:9200
      - 9300:9300
